name: build and validate
on:
  schedule:
    - cron: 30 3 * * 1
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
       # Set fetch-depth: 0 to fetch commit history and tags for use in version calculation
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_READ_USER }}
          password: ${{ secrets.DOCKERHUB_READ_TOKEN }}

      - name: Build with Gradle
        uses: hypertrace/github-actions/gradle@main
        with:
          args: dockerBuildImages

      - name: Run Trivy vulnerability scanner
        uses: hypertrace/github-actions/trivy-image-scan@main
        with:
          image: hypertrace/prometheus-jmx-exporter
          output-mode: github
